LANGUAGE_ISO = {'af': 'af_ZA',
                'am': 'am_ET',
                'ar': 'ar_SA',
                'az': 'az_AZ',
                'be': 'be_BY',
                'bg': 'bg_BG',
                'bs': 'bs_BA',
                'ca': 'ca_ES',
                'cs': 'cs_CZ',
                'cy': 'cy_GB',
                'da': 'da_DK',
                'de': 'de_DE',
                'el': 'el_GR',
                'en': 'en_GB',
                'es': 'es_ES',
                'et': 'et_EE',
                'eo': 'eo',
                'eu': 'eu_ES',
                'fa': 'fa_AF',
                'fi': 'fi_FI',
                'fo': 'fo_FO',
                'fr': 'fr_FR',
                'gl': 'gl_ES',
                'he': 'he_IL',
                'hi': 'hi_IN',
                'hr': 'hr_HR',
                'hu': 'hu_HU',
                'hy': 'hy_AM',
                'id': 'id_ID',
                'is': 'is_IS',
                'it': 'it_IT',
                'ja': 'ja_JP',
                'ko': 'ko_KR',
                'lt': 'lt_LT',
                'lv': 'lv_LV',
                'mi': 'mi',
                'mk': 'mk_MK',
                'ml': 'ml_IN',
                'mn': 'mn_MN',
                'ms': 'ms_MY',
                'mt': 'mt_MT',
                'my': 'my_MM',
                'nl': 'nl_NL',
                'no': 'nb_NO',
                'os': 'os_OS',
                'pl': 'pl_PL',
                'pt': 'pt_PT',
                'ro': 'ro_RO',
                'ru': 'ru_RU',
                'si': 'si_LK',
                'sk': 'sk_SK',
                'sl': 'sl_SI',
                'sq': 'sq_AL',
                'sr': 'sr_RS',
                'sv': 'sv_SE',
                'szl': 'szl',
                'ta': 'ta_IN',
                'te': 'te_IN',
                'tg': 'tg_tj',
                'th': 'th_TH',
                'tr': 'tr_TR',
                'uk': 'uk_UA',
                'uz': 'uz_UZ',
                'vi': 'vi_VN',
                'zh': 'zh_CN'}

LANGUAGE_NAMES = {'Afrikaans': 'af_ZA',
                  'Amharic': 'am_ET',
                  'Arabic': 'ar_SA',
                  'Azerbaijani': 'az_AZ',
                  'Belarusian': 'be_BY',
                  'Bulgarian': 'bg_BG',
                  'Bosnian': 'bs_BA',
                  'Catalan': 'ca_ES',
                  'Czech': 'cs_CZ',
                  'Welsh': 'cy_GB',
                  'Danish': 'da_DK',
                  'German': 'de_DE',
                  'Greek': 'el_GR',
                  'English': 'en_GB',
                  'English (Australia)': 'en_AU',
                  'English (New Zealand)': 'en_NZ',
                  'English (US)': 'en_US',
                  'Spanish': 'es_ES',
                  'Spanish (Argentina)': 'es_AR',
                  'Spanish (Mexico)': 'es_MX',
                  'Estonian': 'et_EE',
                  'Esperanto': 'eo',
                  'Basque': 'eu_ES',
                  'Persian': 'fa_AF',
                  'Persian (Iran)': 'fa_IR',
                  'Finnish': 'fi_FI',
                  'Faroese': 'fo_FO',
                  'French': 'fr_FR',
                  'French (Canada)': 'fr_CA',
                  'Galician': 'gl_ES',
                  'Hebrew': 'he_IL',
                  'Hindi (Devanagiri)': 'hi_IN',
                  'Croatian': 'hr_HR',
                  'Hungarian': 'hu_HU',
                  'Armenian': 'hy_AM',
                  'Indonesian': 'id_ID',
                  'Icelandic': 'is_IS',
                  'Italian': 'it_IT',
                  'Japanese': 'ja_JP',
                  'Korean': 'ko_KR',
                  'Lithuanian': 'lt_LT',
                  'Latvian': 'lv_LV',
                  'Maori': 'mi',
                  'Macedonian': 'mk_MK',
                  'Malayalam': 'ml_IN',
                  'Mongolian (Mongolia)': 'mn_MN',
                  'Malay': 'ms_MY',
                  'Maltese': 'mt_MT',
                  'Burmese': 'my_MM',
                  'Dutch': 'nl_NL',
                  'Norwegian': 'nb_NO',
                  'Ossetic': 'os_OS',
                  'Polish': 'pl_PL',
                  'Portuguese': 'pt_PT',
                  'Portuguese (Brazil)': 'pt_BR',
                  'Romanian': 'ro_RO',
                  'Russian': 'ru_RU',
                  'Sinhala': 'si_LK',
                  'Slovak': 'sk_SK',
                  'Slovenian': 'sl_SI',
                  'Albanian': 'sq_AL',
                  'Serbian': 'sr_RS@latin',
                  'Serbian (Cyrillic)': 'sr_RS',
                  'Swedish': 'sv_SE',
                  'Silesian': 'szl',
                  'Tamil (India)': 'ta_IN',
                  'Telugu': 'te_IN',
                  'Tajik': 'tg_tj',
                  'Thai': 'th_TH',
                  'Turkish': 'tr_TR',
                  'Ukrainian': 'uk_UA',
                  'Uzbek': 'uz_UZ',
                  'Vietnamese': 'vi_VN',
                  'Chinese (Simple)': 'zh_CN',
                  'Chinese (Traditional)': 'zh_TW'}

PLURAL_HEADERS = {'Afrikaans': 'nplurals=2; plural=(n != 1);',
                  'Amharic': 'nplurals=2; plural=(n > 1);',
                  'Arabic': 'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;',
                  'Azerbaijani': 'nplurals=1; plural=0;',
                  'Belarusian': 'nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Bulgarian': 'nplurals=2; plural=(n != 1);',
                  'Bosnian': 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Catalan': 'nplurals=2; plural=(n != 1);',
                  'Czech': 'nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;',
                  'Welsh': 'nplurals=4; plural=(n==1) ? 0 : (n==2) ? 1 : (n != 8 && n != 11) ? 2 : 3;',
                  'Danish': 'nplurals=2; plural=(n != 1);',
                  'German': 'nplurals=2; plural=(n != 1);',
                  'Greek': 'nplurals=2; plural=(n != 1);',
                  'English': 'nplurals=2; plural=(n != 1);',
                  'English (Australia)': 'nplurals=2; plural=(n != 1);',
                  'English (New Zealand)': 'nplurals=2; plural=(n != 1);',
                  'English (US)': 'nplurals=2; plural=(n != 1);',
                  'Esperanto': 'nplurals=2; plural=(n != 1);',
                  'Spanish': 'nplurals=2; plural=(n != 1);',
                  'Spanish (Argentina)': 'nplurals=2; plural=(n != 1);',
                  'Spanish (Mexico)': 'nplurals=2; plural=(n != 1);',
                  'Estonian': 'nplurals=2; plural=(n != 1);',
                  'Basque': 'nplurals=2; plural=(n != 1);',
                  'Persian': 'nplurals=1; plural=0;',
                  'Persian (Iran)': 'nplurals=1; plural=0;',
                  'Finnish': 'nplurals=2; plural=(n != 1);',
                  'Faroese': 'nplurals=2; plural=(n != 1);',
                  'French': 'nplurals=2; plural=(n > 1);',
                  'French (Canada)': 'nplurals=2; plural=(n > 1);',
                  'Galician': 'nplurals=2; plural=(n != 1);',
                  'Hebrew': 'nplurals=2; plural=(n != 1);',
                  'Hindi (Devanagiri)': 'nplurals=2; plural=(n != 1);',
                  'Croatian': 'nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;',
                  'Hungarian': 'nplurals=2; plural=(n != 1);',
                  'Armenian': 'nplurals=2; plural=(n != 1);',
                  'Indonesian': 'nplurals=1; plural=0;',
                  'Icelandic': 'nplurals=2; plural=(n != 1);',
                  'Italian': 'nplurals=2; plural=(n != 1);',
                  'Japanese': 'nplurals=1; plural=0;',
                  'Korean': 'nplurals=1; plural=0;',
                  'Lithuanian': 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Latvian': 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2);',
                  'Maori': 'nplurals=2; plural=(n > 1);',
                  'Macedonian': 'nplurals=2; plural=(n % 10 == 1 && n % 100 != 11) ? 0 : 1;',
                  'Malayalam': 'nplurals=2; plural=(n != 1);',
                  'Mongolian (Mongolia)': 'nplurals=2; plural=(n != 1);',
                  'Malay': 'nplurals=1; plural=0;',
                  'Maltese': 'nplurals=4; plural=(n==1 ? 0 : n==0 || ( n%100>1 && n%100<11) ? 1 : (n%100>10 && n%100<20 ) ? 2 : 3);',
                  'Burmese': 'nplurals=1; plural=0;',
                  'Dutch': 'nplurals=2; plural=(n != 1);',
                  'Norwegian': 'nplurals=2; plural=(n != 1);',
                  'Ossetic': 'nplurals=2; plural=(n != 1);',
                  'Polish': 'nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Portuguese': 'nplurals=2; plural=(n != 1);',
                  'Portuguese (Brazil)': 'nplurals=2; plural=(n > 1);',
                  'Romanian': 'nplurals=3; plural=(n==1?0:(((n%100>19)||((n%100==0)&&(n!=0)))?2:1));',
                  'Russian': 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Sinhala': 'nplurals=2; plural=(n != 1);',
                  'Slovak': 'nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;',
                  'Slovenian': 'nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3);',
                  'Albanian': 'nplurals=2; plural=(n != 1);',
                  'Serbian': 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Serbian (Cyrillic)': 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Swedish': 'nplurals=2; plural=(n != 1);',
                  'Silesian': 'nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Tamil (India)': 'nplurals=2; plural=(n != 1);',
                  'Telugu': 'nplurals=2; plural=(n != 1);',
                  'Tajik': 'nplurals=2; plural=(n != 1);',
                  'Thai': 'nplurals=1; plural=0;',
                  'Turkish': 'nplurals=1; plural=0;',
                  'Ukrainian': 'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);',
                  'Uzbek': 'nplurals=1; plural=0;',
                  'Vietnamese': 'nplurals=1; plural=0;',
                  'Chinese (Simple)': 'nplurals=1; plural=0;',
                  'Chinese (Traditional)': 'nplurals=1; plural=0;'}
